[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

[shell]
program = "ubuntu"

[window]
startup_mode = "Fullscreen"
padding = { x = 0, y = 0 }
decorations = "None"

[keyboard]
bindings = [
    { key = "Space", mods = "Control", chars = "\u0000" },
]
